/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LazyLoad: typeof import('./components/LazyLoad/index.vue')['default']
    MyTabbar: typeof import('./components/MyTabbar/index.vue')['default']
    NavCom: typeof import('./components/NavCom/NavCom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
